# Generated by Django 4.2.4 on 2023-08-04 17:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_uf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_rotulo', models.CharField(blank=True, max_length=255, null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('valor_cobrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_recebido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('documentacao', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
